name: Build Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build requirements
        run: |
          python -m pip install --upgrade build setuptools wheel

      - name: Build package
        run: |
          python -m build
          ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/*
