name: Release Package to Cloudsmith (staging)

# Triggered after build completes
on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: ./dist

      - name: Install jq (for parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Show dist contents
        run: ls -la dist

      - name: Install Cloudsmith CLI via action (OIDC)
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: ${{ vars.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

      - name: Push artifacts to Cloudsmith (staging)
        env:
          CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
        run: |
          # Push all dist files and tag as uploaded
          for f in dist/*; do
            echo "Pushing $f"
            cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/staging "$f" --republish
          done
